# Generated by Django 3.2.3 on 2021-07-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('credit_hour', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ispaid', models.BooleanField()),
                ('isoptional', models.BooleanField()),
            ],
        ),
    ]
