# Generated by Django 3.2.3 on 2021-07-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseDist', '0002_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.IntegerField(default=1),
        ),
    ]
