# Generated by Django 3.2.3 on 2021-07-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseDist', '0004_auto_20210731_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='isOffered',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='seniority',
            field=models.PositiveBigIntegerField(),
        ),
    ]
