# Generated by Django 3.2.3 on 2021-07-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseDist', '0005_auto_20210731_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='id',
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='code_name',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
