# Generated by Django 3.2.3 on 2021-08-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseDist', '0006_auto_20210731_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='CA',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('credit_hour', models.DecimalField(decimal_places=2, max_digits=3)),
                ('frstSetter', models.CharField(max_length=100)),
                ('frstSetter_code_name', models.CharField(max_length=10)),
                ('scndSetter', models.CharField(max_length=100)),
                ('scndSetter_code_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='seniority',
            field=models.PositiveIntegerField(),
        ),
    ]
