# Generated by Django 3.2.3 on 2021-08-01 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseDist', '0007_auto_20210801_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ca',
            name='frstSetter_code_name',
        ),
        migrations.RemoveField(
            model_name='ca',
            name='scndSetter_code_name',
        ),
    ]
