# Generated by Django 3.2.3 on 2021-08-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseDist', '0008_auto_20210801_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvenSem',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('credit_hour', models.DecimalField(decimal_places=2, max_digits=3)),
                ('frstSetter', models.CharField(max_length=100)),
                ('scndSetter', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='CA',
            new_name='OddSem',
        ),
    ]
