# Generated by Django 3.2.3 on 2021-08-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseDist', '0009_auto_20210801_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='evensem',
            name='isoptional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evensem',
            name='ispaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oddsem',
            name='isoptional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oddsem',
            name='ispaid',
            field=models.BooleanField(default=False),
        ),
    ]
