# Generated by Django 3.2.3 on 2021-08-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseDist', '0010_auto_20210801_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='evensem',
            name='isOffered',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='evensem',
            name='isSessional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evensem',
            name='semester',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='evensem',
            name='year',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='oddsem',
            name='isOffered',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='oddsem',
            name='isSessional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oddsem',
            name='semester',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='oddsem',
            name='year',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
