# Generated by Django 3.2.3 on 2021-08-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseDist', '0011_auto_20210801_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evensem',
            name='scndSetter',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='oddsem',
            name='scndSetter',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
